[package]
name = "organic-replay"
version = "0.1.5"
description = "A minimalist, distraction-free document editor designed with forensic integrity."
authors = ["Nikhil Shah"]
license = "GPL-3.0-or-later"
homepage = "https://www.dataproduct.company"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "organic_replay_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "organic-replay"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rfd = "0.14"
rusqlite = { version = "0.31", features = ["bundled"] }
sha2 = "0.10"
zip = { version = "0.6", default-features = false, features = ["deflate"] }
chrono = "0.4"

[package.metadata.bundle]
copyright = "Copyright (C) 2026 Data Product Company LLC. All rights reserved."
